name = "cloudmail"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
keep_vars = true
workers_dev = true
routes = [
  { pattern = "b-d.indevs.in", custom_domain = true, zone_id = "fc36ab702dab1ec1c0ec10dce375279c" },
]

[assets]
directory = "./frontend/dist/"
binding = "ASSETS"
run_worker_first = true

# email receiving binding (required for Workers to receive emails via Email Routing)
send_email = [
  { name = "SEND_MAIL" },
]

# enable cron for auto clean up expired emails (runs daily at midnight)
[triggers]
crons = ["0 0 * * *"]

[vars]
PREFIX = "tmp"
DEFAULT_DOMAINS = ["b-d.indevs.in"]
DOMAINS = ["b-d.indevs.in"]
JWT_SECRET = "2ec70ca66a2c693f8f08f1da1d7feb09953a32d1c72bf9f47f1f24200dbcfcfb"
ADMIN_PASSWORDS = ["2ec70ca66a2c693f8f08f1da1d7feb09953a32d1c72bf9f47f1f24200dbcfcfb"]
BLACK_LIST = ""
ENABLE_USER_CREATE_EMAIL = true
ENABLE_USER_DELETE_EMAIL = true
ENABLE_AUTO_REPLY = false
ENABLE_USER_REGISTRATION = true

[[d1_databases]]
binding = "DB"
database_name = "cloudflare-temp-email"
database_id = "c3686961-2c99-42a8-af48-672adff17c38"
